spring.application.name=Smart-Contact-Manager
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.thymeleaf.enabled=true
spring.jpa.hibernate.ddl-auto=update
sql_require_primary_key=OFF